spring:
  application:
    name: devmatch
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__KAKAO__CLIENT_ID}
            client-secret: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__KAKAO__CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          google:
            client-id: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__GOOGLE__CLIENT_ID}
            client-secret: ${SPRING__SECURITY__OAUTH2__CLIENT__REGISTRATION__GOOGLE__CLIENT_SECRET}
            scope: profile
            client-name: Google
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${SPRING__AI__OPENAI__API_KEY}
      chat:
        options:
          model: meta-llama/llama-4-maverick-17b-128e-instruct
          temperature: 0

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: when-authorized

custom:
  jwt:
    secret: ${CUSTOM__JWT__SECRET}
    expirationSeconds: "#{60*20}"

logging:
  level:
    com.devmatch.backend: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
